name: Image Scan

on:
    pull_request:
        branches:
            - main

    workflow_dispatch:
        inputs:
            image-ref:
                description: "The name of the image (Default will get this repositories latest image)"
            branch_hash:
                description: Branch sha or revision to deploy (Defaults to branch sha)

jobs:
    image-scan:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - name: Scanning Image ${{ github.repository }}:${{ inputs.branch_hash || github.sha}}
              uses: hathitrust/github_actions/scan-image@DEV-1240
              with:
                # image-ref: ghcr.io/${{ github.repository || inputs.image-ref }}:${{ inputs.branch_hash || github.sha}}
                image-ref: ghcr.io/${{ github.repository || inputs.image-ref }}:${{ inputs.branch_hash || 'e688a4b471d6956520cca87a7626bacfbc5f3ec4'}}
