name: Tag Latest Image with Release Version

on:
  release:
    types: [released]

jobs:
  tag-release:
    runs-on: ubuntu-latest
    steps:
      - uses: hathitrust/github_actions/.github/workflows/tag-release.yml@167b911da53b48b05280b6dfb99a235ac457f255#v1.8.0
        with:
          registry_token: ${{ github.token }}
          existing_tag: ghcr.io/${{ github.repository }}:${{ github.sha }}
          image: ghcr.io/${{ github.repository }}
          new_tag: ${{ github.event.release.tag_name }}
