name: Run Tests on Code
# Use the python unit tests workflow
# Built From https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-python#introduction

on:
  workflow_dispatch:
    inputs:
      ref:
        description: Revision or Branch to build
        default: main
  workflow_call:
    inputs:
      ref:
        description: Revision or Branch to build
        default: main
        required: true
        type: string

jobs:
  Test-Code:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{inputs.ref}}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip list

      - name: Test Python Code
        run: python -m unittest test_python_server.py